config/routes.rb
Rails.application.routes.draw do
  resources :healers

  resources :users

  resources :healings

end

app/models/healer.rb
class Healer < User
end

app/models/healing.rb
class Healing < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :healings
  has_many :healers, through: :healings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/healers_controller.rb
class HealersController < ApplicationController
  before_action :set_healer, only: [:show, :edit, :update, :destroy]

  # GET /healers
  # GET /healers.json
  def index
    @healers = Healer.all
  end

  # GET /healers/1
  # GET /healers/1.json
  def show
  end

  # GET /healers/new
  def new
    @healer = Healer.new
  end

  # GET /healers/1/edit
  def edit
  end

  # POST /healers
  # POST /healers.json
  def create
    @healer = Healer.new(healer_params)

    respond_to do |format|
      if @healer.save
        format.html { redirect_to @healer, notice: 'Healer was successfully created.' }
        format.json { render :show, status: :created, location: @healer }
      else
        format.html { render :new }
        format.json { render json: @healer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /healers/1
  # PATCH/PUT /healers/1.json
  def update
    respond_to do |format|
      if @healer.update(healer_params)
        format.html { redirect_to @healer, notice: 'Healer was successfully updated.' }
        format.json { render :show, status: :ok, location: @healer }
      else
        format.html { render :edit }
        format.json { render json: @healer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /healers/1
  # DELETE /healers/1.json
  def destroy
    @healer.destroy
    respond_to do |format|
      format.html { redirect_to healers_url, notice: 'Healer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_healer
      @healer = Healer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def healer_params
      params.require(:healer).permit(:certlevel)
    end
end

app/controllers/healings_controller.rb
class HealingsController < ApplicationController
  before_action :set_healing, only: [:show, :edit, :update, :destroy]

  # GET /healings
  # GET /healings.json
  def index
    @healings = Healing.all
  end

  # GET /healings/1
  # GET /healings/1.json
  def show
  end

  # GET /healings/new
  def new
    @healing = Healing.new
  end

  # GET /healings/1/edit
  def edit
  end

  # POST /healings
  # POST /healings.json
  def create
    @healing = Healing.new(healing_params)

    respond_to do |format|
      if @healing.save
        format.html { redirect_to @healing, notice: 'Healing was successfully created.' }
        format.json { render :show, status: :created, location: @healing }
      else
        format.html { render :new }
        format.json { render json: @healing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /healings/1
  # PATCH/PUT /healings/1.json
  def update
    respond_to do |format|
      if @healing.update(healing_params)
        format.html { redirect_to @healing, notice: 'Healing was successfully updated.' }
        format.json { render :show, status: :ok, location: @healing }
      else
        format.html { render :edit }
        format.json { render json: @healing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /healings/1
  # DELETE /healings/1.json
  def destroy
    @healing.destroy
    respond_to do |format|
      format.html { redirect_to healings_url, notice: 'Healing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_healing
      @healing = Healing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def healing_params
      params.require(:healing).permit(:price, :session_time, :comment)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :full_name, :password, :email, :age, :location, :bio, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/healers_helper.rb
module HealersHelper
end

app/helpers/healings_helper.rb
module HealingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/healers/_form.html.erb
<%= form_for(@healer) do |f| %>
  <% if @healer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@healer.errors.count, "error") %> prohibited this healer from being saved:</h2>

      <ul>
      <% @healer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :certlevel %><br>
    <%= f.text_field :certlevel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/healers/edit.html.erb
<h1>Editing healer</h1>

<%= render 'form' %>

<%= link_to 'Show', @healer %> |
<%= link_to 'Back', healers_path %>

app/views/healers/index.html.erb
<h1>Listing healers</h1>

<table>
  <thead>
    <tr>
      <th>Certlevel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @healers.each do |healer| %>
      <tr>
        <td><%= healer.certlevel %></td>
        <td><%= link_to 'Show', healer %></td>
        <td><%= link_to 'Edit', edit_healer_path(healer) %></td>
        <td><%= link_to 'Destroy', healer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Healer', new_healer_path %>

app/views/healers/new.html.erb
<h1>New healer</h1>

<%= render 'form' %>

<%= link_to 'Back', healers_path %>

app/views/healers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Certlevel:</strong>
  <%= @healer.certlevel %>
</p>

<%= link_to 'Edit', edit_healer_path(@healer) %> |
<%= link_to 'Back', healers_path %>

app/views/healings/_form.html.erb
<%= form_for(@healing) do |f| %>
  <% if @healing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@healing.errors.count, "error") %> prohibited this healing from being saved:</h2>

      <ul>
      <% @healing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :session_time %><br>
    <%= f.datetime_select :session_time %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/healings/edit.html.erb
<h1>Editing healing</h1>

<%= render 'form' %>

<%= link_to 'Show', @healing %> |
<%= link_to 'Back', healings_path %>

app/views/healings/index.html.erb
<h1>Listing healings</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Session time</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @healings.each do |healing| %>
      <tr>
        <td><%= healing.price %></td>
        <td><%= healing.session_time %></td>
        <td><%= healing.comment %></td>
        <td><%= link_to 'Show', healing %></td>
        <td><%= link_to 'Edit', edit_healing_path(healing) %></td>
        <td><%= link_to 'Destroy', healing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Healing', new_healing_path %>

app/views/healings/new.html.erb
<h1>New healing</h1>

<%= render 'form' %>

<%= link_to 'Back', healings_path %>

app/views/healings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @healing.price %>
</p>

<p>
  <strong>Session time:</strong>
  <%= @healing.session_time %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @healing.comment %>
</p>

<%= link_to 'Edit', edit_healing_path(@healing) %> |
<%= link_to 'Back', healings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Distantph</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Full name</th>
      <th>Password</th>
      <th>Email</th>
      <th>Age</th>
      <th>Location</th>
      <th>Bio</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.full_name %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.age %></td>
        <td><%= user.location %></td>
        <td><%= user.bio %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>